<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="My_Program" Id="{0a423137-b916-4f33-8548-42aef392f727}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM My_Program
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="My_Program">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>